### PR TITLE
add nifty new hex logo

### PR DESCRIPTION
**Pull request by bhamail**
Add logo file and display it in README.md

cc @bhamail / @DarthHater / @brittanybelle / @adrianpowell / @csgillespie

### CODE REVIEW

**Comment by csgillespie** [comment]
The `md` file is generated from the `.Rmd` file. So you should add it to the README.Rmd file and `knit` it.

**Comment by brent-spiner** [comment]
@csgillespie should be good to go now!

**Comment by DarthHater** [comment]
@csgillespie should be good to go now!

**Comment by bhamail** [comment]
Doh! And it even politely says: "Please edit that file". Thanks for the fix @DarthHater.

**Comment by bhamail** [comment]
If no one objects, I'd like to merge this.

**Pull request merged**
